name: Update Main Repository on Frontend Changes

on:
  push:
    branches:
      - main  # Или любая другая ветка, используемая для разработки Frontend

jobs:
  update-main-repo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Frontend Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Необходимо для получения полной истории

      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Clone Main Repository
        uses: actions/checkout@v3
        with:
          repository: AnnaKharatova/PartnersMap # Замените на ваш основной репозиторий
          token: ${{ secrets.MAIN_REPO_PAT }}
          path: main-repo

      - name: Update Submodule Reference
        run: |
          cd main-repo
          git submodule update --remote https://github.com/AnnaKharatova/PartnersMap  # Замените 'frontend' на путь к вашему субмодулю, если отличается
          git add frontend
          git commit -m "Update Frontend submodule to latest commit" || echo "No changes to commit"
          git push origin main  # Убедитесь, что ветка правильная
